name: CI
on:
  pull_request:
    branches: [main]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: pip install flake8
      - name: Lint with flake8
        run: flake8 . --exclude=venv --max-line-length=120
      - run: echo "Backend CI Passed"
